language: node_js
addons:
  ssh_known_hosts: hdgh0g.com
before_script:
  - openssl aes-256-cbc -K $encrypted_2308638af99e_key -iv $encrypted_2308638af99e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
script:
  - npm i
  - npm run build
  - rsync -r --delete-after --quiet ./build travis@hdgh0g.com:/home/staticsite/main
notifications:
  email: false
